In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
# FOOOF included, no z-scoring
edition = '/Volumes/psp_data/PSP/Pupil_Preprocessed_2024-06-17/'

In [39]:
cov = pd.read_hdf(join(edition, 'PowerFrequencies', 'CoV.hdf'), key='data')
cov = cov.loc[(cov.session == 'Baseline')&(cov.group.isin(['PSP', 'PD', 'Control']))&(cov.condition == 'bp_non_normalized')]

cov = cov.groupby(['group', 'subject']).mean().reset_index() #average per subject across runs

In [48]:
average_diam = cov.groupby('group').mean().round(1)
average_diam

         mean  std
group
Control  62.2  4.6
PD       58.9  5.2
PSP      57.5  2.5

In [49]:
std_diam = cov.groupby('group').std()
std_diam

              mean       std
group
Control  12.460099  1.773695
PD       10.456221  1.463437
PSP      14.961129  1.344412

In [58]:
average_diam.loc['Control', 'mean'].round(1)

62.2

In [43]:
# ANOVA mit scipy
f_stat, p_val = stats.f_oneway(cov.loc[cov.group== 'PSP', 'mean'].values,
                               cov.loc[cov.group== 'PD', 'mean'].values,
                               cov.loc[cov.group== 'Control', 'mean'].values)

print("F-Wert:", f_stat, "p-Wert:", p_val)

F-Wert: 0.46295060332096233 p-Wert: 0.6326736203749446

In [68]:
'The mean pupil diameter did not significantly differ across groups (PSP {0} ± {3} pixel, PD {1} ±{4} pixel, HC {2} ±{5} pixel; F={6}, p={7})'.format(average_diam.loc['PSP', 'mean'].round(1),
                                                                                                                                        average_diam.loc['PD', 'mean'].round(1),
                                                                                                                                        average_diam.loc['Control', 'mean'].round(1),
                                                                                                                                        std_diam.loc['PSP', 'mean'].round(1),
                                                                                                                                       std_diam.loc['PD', 'mean'].round(1),
                                                                                                                                       std_diam.loc['Control', 'mean'].round(1),
                                                                                                                                                     f_stat.round(2),
                                                                                                                                                     p_val.round(2))

'The mean pupil diameter did not significantly differ across groups (PSP 57.5 ± 15.0 pixel, PD 58.9 ±10.5 pixel, HC 62.2 ±12.5 pixel; F=0.46, p=0.63)'